name: mlapp_demo

dependencies:
  - python=3.10
  - pip
  - ipython
  - jupyter
  
  # For accessing files in AWS S3 buckets
  - s3fs 
 
  # For packaging
  - wheel

  # For visualisation
  - matplotlib
  - seaborn

  # For model construction
  - numpy
  - pandas
  - scipy
  - scikit-learn=1.3.2
  - requests
  - flask

  - streamlit
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - xgboost
  - boto3
  - plotly
  - statsmodels  

  - pip:
    - watermark
    - pytest
    - python-dotenv
